//Default exports:
//rippleBlur = 2,
//speed = 500,
//color = '#fff',
//fontSize = '1rem',
//bgColor = '93, 120, 255',
//bgHover = bgColor,
//bgActive = bgColor,
//rippleColor = '#264169',
//round = '0.5rem',
//height = 60,
//width = 250,
//sizeIn = 20,
//opacityIn = 0.2,
//shadow = 'none',
//shadowHover = 'none',
//shadowActive = 'none';
export const bigBlue = {
	rippleBlur: 2,
	speed: 500,
	color: '#fff',
	colorHover: '#fff',
	fontSize: '1.04em',
	bgColor: '20,115,230',
	bgColorOpacity: 1,
	bgHover: '20,115,230',
	bgActive: '20,115,230',
	rippleColor: '#000',
	round: '100px',
	height: '50px',
	width: 'auto',
	margin: '10px 20px',
	padding: '0px 32px',
	sizeIn: 20,
	opacityIn: 0.2,
	shadow: 'none',
	shadowHover: 'none',
	shadowActive: 'none',
	secondaryBGColor: '#fff',
	secondaryBorder: 'solid 3px #F5F7F5',
	secondaryColor: '#5A576A'
}
export const bigPink = {
	rippleBlur: 2,
	speed: 500,
	color: '#fff',
	colorHover: '#fff',
	fontSize: '1.04em',
	bgColor: '255,0,122',
	bgColorOpacity: 1,
	bgHover: '255,0,122',
	bgActive: '255,0,122',
	rippleColor: '#000',
	round: '100px',
	height: '50px',
	width: 'auto',
	margin: '10px 20px',
	padding: '0px 32px',
	sizeIn: 20,
	opacityIn: 0.2,
	shadow: 'none',
	shadowHover: 'none',
	shadowActive: 'none',
	secondaryBGColor: '#fff',
	secondaryBorder: 'solid 3px #F5F7F5',
	secondaryColor: '#5A576A'
}
export const basic = {
	rippleBlur: 2,
	speed: 500,
	color: '#1A1C1A',
	fontSize: '1em',
	fontWeight: 'bold',
	border: 'solid 4px #F5F7F5',
	bgColor: '255, 255, 255',
	bgColorOpacity: 1,
	bgHover: '245, 247, 245',
	bgActive: '255, 255, 255',
	rippleColor: '#000',
	round: '10px',
	height: '60px',
	width: '',
	margin: '0px',
	padding: '0px 20px',
	sizeIn: 20,
	opacityIn: 0.2,
	shadow: 'none',
	shadowHover: 'none',
	shadowActive: 'none'
}
export const simple = {
	rippleBlur: 2,
	speed: 500,
	color: '#1A1C1A',
	fontSize: '1em',
	fontWeight: 'bold',
	border: 'solid 4px #F5F7F5',
	bgColor: '255, 255, 255',
	bgColorOpacity: 1,
	bgHover: '245, 247, 245',
	bgActive: '255, 255, 255',
	rippleColor: '#000',
	round: '10px',
	height: '60px',
	width: '',
	margin: '0px',
	padding: '0px 20px',
	sizeIn: 20,
	opacityIn: 0.2,
	shadow: 'none',
	shadowHover: 'none',
	shadowActive: 'none'
}
export const disabled = {
	rippleBlur: 2,
	speed: 500,
	color: '#bebfbe',
	colorActive: '#bebfbe',
	colorHover: '#bebfbe',
	fontSize: '1em',
	fontWeight: 'bold',
	border: 'solid 4px #F5F7F5',
	bgColor: '245, 247, 245',
	bgColorOpacity: 1,
	bgHover: '245, 247, 245',
	bgActive: '245, 247, 245',
	rippleColor: '#000',
	round: '10px',
	height: '60px',
	width: '',
	margin: '0px',
	padding: '0px 20px',
	sizeIn: 20,
	opacityIn: 0.2,
	shadow: 'none',
	shadowHover: 'none',
	shadowActive: 'none'
}
export const transparent = {
	rippleBlur: 2,
	speed: 500,
	color: '#1A1C1A',
	colorHover: '#1ba8f1',
	fontSize: '1em',
	fontWeight: 'bold',
	border: '',
	bgColor: '',
	bgColorOpacity: 1,
	bgHover: '',
	bgActive: '',
	rippleColor: '#000',
	round: '',
	height: '60px',
	width: '',
	margin: '0px',
	padding: '0px 20px',
	sizeIn: 20,
	opacityIn: 0.2,
	shadow: 'none',
	shadowHover: 'none',
	shadowActive: 'none'
}
export const underline = {
	rippleBlur: 2,
	speed: 500,
	color: '#1A1C1A',
	colorHover: '#1ba8f1',
	fontSize: '0.875em',
	fontWeight: 'normal',
	border: '',
	bgColor: '',
	bgColorOpacity: 1,
	bgHover: '',
	bgActive: '',
	rippleColor: '#000',
	round: '',
	height: '60px',
	width: '',
	margin: '0px',
	padding: '0px 10px 0px 0px',
	sizeIn: 20,
	opacityIn: 0.2,
	shadow: 'none',
	shadowHover: 'none',
	shadowActive: 'none',
	align: 'flex-end',
	decoration: 'underline'
}
export const large = {
	rippleBlur: 2,
	speed: 500,
	color: '#000',
	colorActive: '#000',
	colorHover: '#000',
	fontSize: '1em',
	fontWeight: 'bold',
	border: 'solid 2px #000',
	bgColor: '0, 227, 198',
	bgColorOpacity: 1,
	bgHover: '0, 227, 198',
	bgActive: '0, 227, 198',
	rippleColor: '#000',
	round: '8px',
	height: '40px',
	width: '',
	margin: '0px',
	padding: '0px 20px',
	sizeIn: 20,
	opacityIn: 0.2,
	shadow: 'none',
	shadowHover: 'none',
	shadowActive: 'none'
}
export const mini = {
	rippleBlur: 2,
	speed: 500,
	color: '#000',
	colorActive: '#000',
	colorHover: '#000',
	fontSize: '0.875em',
	fontWeight: 'bold',
	border: 'solid 2px #000',
	bgColor: '0, 227, 198',
	bgColorOpacity: 1,
	bgHover: '0, 227, 198',
	bgActive: '0, 227, 198',
	rippleColor: '#000',
	round: '8px',
	height: '40px',
	width: '',
	margin: '0px',
	padding: '0px 14px',
	sizeIn: 20,
	opacityIn: 0.2,
	shadow: 'none',
	shadowHover: 'none',
	shadowActive: 'none'
}
export const clearMini = {
	rippleBlur: 2,
	speed: 500,
	color: '#000',
	colorActive: '#000',
	colorHover: '#000',
	fontSize: '0.875em',
	fontWeight: 'bold',
	border: 'solid 2px #000',
	bgColor: '',
	bgColorOpacity: 1,
	bgHover: '',
	bgActive: '',
	rippleColor: '#000',
	round: '8px',
	height: '40px',
	width: '',
	margin: '0px',
	padding: '0px 14px',
	sizeIn: 20,
	opacityIn: 0.2,
	shadow: 'none',
	shadowHover: 'none',
	shadowActive: 'none'
}
export const clear = {
	rippleBlur: 2,
	speed: 500,
	color: '#000',
	colorActive: '#000',
	colorHover: '#000',
	fontSize: '1em',
	fontWeight: 'bold',
	border: 'solid 2px #000',
	bgColor: '',
	bgColorOpacity: 1,
	bgHover: '',
	bgActive: '',
	rippleColor: '#000',
	round: '8px',
	height: '40px',
	width: '',
	margin: '0px',
	padding: '0px 20px',
	sizeIn: 20,
	opacityIn: 0.2,
	shadow: 'none',
	shadowHover: 'none',
	shadowActive: 'none'
}
export const simpleRoundSmall = {
	rippleBlur: 2,
	speed: 500,
	color: '#1A1C1A',
	fontSize: '0.85em',
	fontWeight: 'bold',
	border: 'solid 4px #F5F7F5',
	bgColor: '255, 255, 255',
	bgColorOpacity: 1,
	bgHover: '245, 247, 245',
	bgActive: '255, 255, 255',
	rippleColor: '#000',
	round: '60px',
	height: '40px',
	width: '',
	margin: '10px 0px',
	padding: '0px 15px',
	sizeIn: 20,
	opacityIn: 0.2,
	shadow: 'none',
	shadowHover: 'none',
	shadowActive: 'none'
}
export const icon = {
	rippleBlur: 2,
	speed: 500,
	color: '#1A1C1A',
	colorHover: '#1ba8f1',
	fontSize: '1em',
	fontWeight: 'bold',
	border: '',
	bgColor: '',
	bgColorOpacity: 1,
	bgHover: '',
	bgActive: '',
	rippleColor: '#000',
	round: '',
	height: '60px',
	width: '',
	margin: '0px',
	padding: '0px 20px',
	sizeIn: 20,
	opacityIn: 0.2,
	shadow: 'none',
	shadowHover: 'none',
	shadowActive: 'none'
}
